//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSAchievementTracker.Persistence
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AchievementsDatabaseEntities : DbContext
    {
        public AchievementsDatabaseEntities()
            : base("name=AchievementsDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievement> Achievements { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<QuestReq> QuestReqs { get; set; }
        public virtual DbSet<SkillReq> SkillReqs { get; set; }
        public virtual DbSet<Subcategory> Subcategories { get; set; }
    }
}
